name: validate-topics-json
on:
  pull_request:
    paths:
     - 'data/topics.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |
          npm run validate:topics
    
      - name: Report Success
        run: echo "topics.json validation ran successfully!"
