name: validate-json

on:
  workflow_call:
    inputs:
      type:
        description: 'The type of json date file to process'
        required: true
        type: string
        default: 'profiles'

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |

          # Don't exit on first error
          set +e

          # Run validation and capture the output
          npm run validate:${{ inputs.type }} 2> error.log 

          # Output the validation result to an environment variable
          if [[ -s error.log ]]; then
            echo "Error = $(cat error.log)"
            echo "JSON_VALIDATION_RESULT=$(cat error.log)" >> $GITHUB_ENV
            exit 1
          fi


      - name: Add GitHub Comment
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `\`${{ inputs.type }}.json\` failed validation with the following error:

                  ${{ env.JSON_VALIDATION_RESULT }}
              `
            })
        env:
          JSON_VALIDATION_RESULT: ${{ env.JSON_VALIDATION_RESULT }}