name: validate-profiles-json
on:
  pull_request:
    paths:
     - 'data/profiles.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |
          npm run validate:profiles

      - name: Add GitHub Comment
        if: github.event_name == 'pull_request' && failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ env.ISSUE_NBR }}
          body: |
            Error validating profiles. Please check the output of the validation task for details.
    
      - name: Report Success
        run: echo "profiles.json validation ran successfully!"
