name: validate-profiles-json
on:
  pull_request:
    paths:
     - 'data/profiles.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-profiles-json:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |
          # Run validation and capture the output
          npm run validate:profiles 2>&1 | tee output.log

          # Output the validation result to an environment variable
          if [[ -s output.log ]]; then
            echo "JSON_VALIDATION_RESULT=$(cat output.log)" >> $GITHUB_ENV
          fi

      - name: Add GitHub Comment
        if: github.event_name == 'pull_request' && failure()
        uses: peter-evans/create-or-update-comment@v4
        with:
          issue-number: ${{ github.event.number }}
          body: |
            `profiles.json` failed validation with the following output:

            ```
            ${{ env.JSON_VALIDATION_RESULT }}
            ```
        env:
          JSON_VALIDATION_RESULT: ${{ env.JSON_VALIDATION_RESULT }}

      - name: Display Validation Errors
        if: env.JSON_VALIDATION_RESULT != ''
        run: |
          echo "Validation error: $JSON_VALIDATION_RESULT"