name: validate-profiles-json

on:
  pull_request:
    paths:
     - 'data/profiles.json'
  workflow_dispatch:

jobs:
  validate-json:
    uses: ./validate-json.yml@validate-json
    with:
      type: profiles