name: validate-profiles-json
on:
  pull_request:
    paths:
     - 'data/profiles.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-profiles-json:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |

          set +e

          # Run validation and capture the output
          npm run validate:profiles 2> /tmp/error.log 

          # Output the validation result to an environment variable
          if [[ -s /tmp/error.log ]]; then
            echo "JSON_VALIDATION_RESULT=$(cat /tmp/error.log)" >> $GITHUB_ENV
            exit 1
          fi


      - name: Add GitHub Comment
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `\`profiles.json\` failed validation with the following error:

                  ${{ env.JSON_VALIDATION_RESULT }}
              `
            })
        env:
          JSON_VALIDATION_RESULT: ${{ env.JSON_VALIDATION_RESULT }}