name: validate-topics-json
on:
  pull_request:
    paths:
     - 'data/topics.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-topics-json:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          cache: npm

      - name: Install Dependencies
        run: npm ci --no-fund --no-audit

      - name: Validate JSON
        run: |
          node scripts/validate-json.mjs topics

      - name: Add GitHub Comment
        if: github.event_name == 'pull_request' && failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `\`topics.json\` failed validation, see the validation rule results for more details.`
            })