name: validate-profiles-json

on:
  pull_request:
    paths:
     - 'data/profiles.json'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  validate-json:
    uses: ./.github/workflows/validate-json.yml
    with:
      type: profiles